#!/bin/sh
if  [[ $1 = "-m" ]]; then (
    echo "Mounting sdb..."
    mount /dev/sdb1 /mnt/sourcemage/
    mount /dev/sdb2 /mnt/backup
    mount /dev/sdb3 /mnt/gentoo/
    mount /dev/sdb5 /mnt/kali/
    mount /dev/sdb6 /mnt/opensuse/
    )

elif  [[ $1 = "-u" ]]; then (
    echo "Umounting sdb..."
    umount /mnt/sourcemage/
    umount /mnt/backup
    umount /mnt/gentoo/
    umount /mnt/kali/
    umount /mnt/opensuse/
    )

else
    echo -e "\e[1m\e[31mUse -m to mount sdb Use -u to umount sdb\e[0m"
fi
